"""Deterministic grounding context for future model consumption, without an LLM."""

from __future__ import annotations

import json
from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

from .evidence import EvidenceBundle, EvidenceItem


GROUNDING_INSTRUCTIONS = """GROUNDING RULES
- Use the supplied scriptural evidence when making scriptural claims.
- Do not invent quotations or attribute teachings to unsupported verses.
- Distinguish direct scriptural teaching from interpretation and modern application.
- Cite relevant canonical verse identifiers.
- If the supplied evidence is insufficient, acknowledge the limitation rather than inventing support."""


@dataclass(frozen=True)
class GroundingContext:
    """Ordered scriptural evidence and rules; it never generates interpretation or application."""

    query: str
    evidence_items: tuple[EvidenceItem, ...]
    retrieval_configuration: Mapping[str, Any] | None = None

    def __post_init__(self) -> None:
        if not isinstance(self.query, str) or not self.query.strip():
            raise ValueError("query must be a non-empty string")
        object.__setattr__(self, "evidence_items", tuple(self.evidence_items))

    @classmethod
    def from_evidence_bundle(cls, bundle: EvidenceBundle) -> "GroundingContext":
        """Transport evidence without reranking, deduplicating, summarizing, or interpreting it."""
        return cls(bundle.query, bundle.items, bundle.retrieval_configuration)

    def to_prompt_context(self) -> str:
        """Serialize complete evidence deterministically for a future provider-neutral prompt layer."""
        lines = [
            "=== GROUNDING INSTRUCTIONS ===",
            GROUNDING_INSTRUCTIONS,
            "=== USER QUESTION ===",
            self.query,
            "=== RETRIEVAL CONFIGURATION ===",
            _serialize_value(self.retrieval_configuration),
            "=== SCRIPTURAL EVIDENCE ===",
        ]
        if not self.evidence_items:
            lines.append("NO SCRIPTURAL EVIDENCE RETRIEVED.")
        for rank, item in enumerate(self.evidence_items, start=1):
            lines.extend(
                [
                    f"--- EVIDENCE ITEM {rank} ---",
                    f"document_id: {item.document_id}",
                    f"canonical_passage_id: {_display(item.passage_id)}",
                    f"chapter: {_display(item.chapter)}",
                    f"verse: {_display(item.verse)}",
                    f"text_layer: {_display(item.text_layer)}",
                    f"relevance_score: {item.score!r}",
                    f"source: {_serialize_value(item.source)}",
                    f"metadata: {_serialize_value(item.metadata)}",
                    "retrieved_text:",
                    item.text,
                    f"--- END EVIDENCE ITEM {rank} ---",
                ]
            )
        lines.extend(
            [
                "=== BOUNDARY ===",
                "SCRIPTURAL EVIDENCE: retrieved corpus text and traceable metadata above.",
                "INTERPRETATION: not generated by GroundingContext.",
                "APPLICATION: not generated by GroundingContext.",
            ]
        )
        return "\n".join(lines)


def _display(value: object | None) -> str:
    return "null" if value is None else str(value)


def _serialize_value(value: Any) -> str:
    return json.dumps(_json_value(value), ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def _json_value(value: Any) -> Any:
    if isinstance(value, Mapping):
        return {str(key): _json_value(nested_value) for key, nested_value in value.items()}
    if isinstance(value, tuple | list):
        return [_json_value(item) for item in value]
    if isinstance(value, frozenset | set):
        return sorted(_json_value(item) for item in value)
    return value
