"""Offline tests for deterministic, model-independent grounding context."""

from __future__ import annotations

import sys
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "Backend"))

from vedavault_retrieval import (  # noqa: E402
    GROUNDING_INSTRUCTIONS,
    EvidenceBundle,
    GroundingContext,
    RetrievalDocument,
    RetrievalResult,
)


class GroundingContextTests(unittest.TestCase):
    def setUp(self) -> None:
        self.metadata = {
            "passage_id": "BG_02_47",
            "chapter": 2,
            "verse": 47,
            "text_layer": "translations",
            "source": {"source_id": "gita-source", "raw_file": "gita.json"},
            "provenance": {"source_id": "gita-source", "raw_field": "translation"},
        }
        self.results = [
            RetrievalResult(RetrievalDocument("first", "Act without attachment.", self.metadata), 0.91),
            RetrievalResult(
                RetrievalDocument(
                    "second",
                    "The Self is eternal.",
                    {"passage_id": "BG_02_20", "chapter": 2, "verse": 20, "text_layer": "translations", "source": {"source_id": "other"}},
                ),
                0.73,
            ),
        ]
        self.bundle = EvidenceBundle.from_retrieval(
            "How should I act?", self.results, retrieval_configuration={"text_layers": ["translations"]}
        )

    def test_conversion_preserves_query_evidence_order_and_traceability(self) -> None:
        context = GroundingContext.from_evidence_bundle(self.bundle)
        self.assertEqual(context.query, "How should I act?")
        self.assertEqual([item.document_id for item in context.evidence_items], ["first", "second"])
        first = context.evidence_items[0]
        self.assertEqual((first.passage_id, first.chapter, first.verse), ("BG_02_47", 2, 47))
        self.assertEqual((first.text, first.text_layer, first.score), ("Act without attachment.", "translations", 0.91))
        self.assertEqual(first.source["source_id"], "gita-source")
        self.assertEqual(first.metadata["provenance"]["raw_field"], "translation")

    def test_serialization_is_deterministic_complete_and_delimited(self) -> None:
        context = GroundingContext.from_evidence_bundle(self.bundle)
        serialized = context.to_prompt_context()
        self.assertEqual(serialized, context.to_prompt_context())
        self.assertIn("=== USER QUESTION ===\nHow should I act?", serialized)
        self.assertIn("--- EVIDENCE ITEM 1 ---", serialized)
        self.assertIn("--- END EVIDENCE ITEM 2 ---", serialized)
        self.assertIn("canonical_passage_id: BG_02_47", serialized)
        self.assertIn("chapter: 2", serialized)
        self.assertIn("verse: 47", serialized)
        self.assertIn("text_layer: translations", serialized)
        self.assertIn("relevance_score: 0.91", serialized)
        self.assertIn('"raw_field":"translation"', serialized)
        self.assertIn('"source_id":"gita-source"', serialized)
        self.assertIn("Act without attachment.", serialized)
        self.assertIn(GROUNDING_INSTRUCTIONS, serialized)
        self.assertIn("INTERPRETATION: not generated by GroundingContext.", serialized)
        self.assertIn("APPLICATION: not generated by GroundingContext.", serialized)

    def test_empty_evidence_is_explicit_and_does_not_fabricate_support(self) -> None:
        context = GroundingContext.from_evidence_bundle(EvidenceBundle.from_retrieval("What is dharma?", []))
        self.assertEqual(context.evidence_items, ())
        self.assertIn("NO SCRIPTURAL EVIDENCE RETRIEVED.", context.to_prompt_context())

    def test_conversion_does_not_mutate_bundle_and_equivalent_bundles_match(self) -> None:
        first = GroundingContext.from_evidence_bundle(self.bundle)
        second = GroundingContext.from_evidence_bundle(
            EvidenceBundle.from_retrieval("How should I act?", list(self.results), self.bundle.retrieval_configuration)
        )
        self.metadata["source"]["source_id"] = "changed-after-conversion"
        self.assertEqual(first.evidence_items[0].source["source_id"], "gita-source")
        self.assertEqual(first, second)


if __name__ == "__main__":
    unittest.main()
